"""Bookkeeping for the wiki layer (wiki/SCHEMA.md): the jobs that need rules, not a model.

The wiki sits on top of the library (library/: sources, appraised.md, claims_en.md) and never changes it.
Every fact in the wiki cites a claim-id from claims_en.md; this script keeps the parts that can be
derived mechanically (each source page's facts block, index.md, log.md) and checks the rest.

Usage (from the platform/ folder):
  python .claude/scripts/wiki.py status                 what ingest still has to do
  python .claude/scripts/wiki.py refresh                create stub pages for new sources, rewrite every
                                                        generated block and index.md
  python .claude/scripts/wiki.py lint                   links, citations, orphans, unsourced numbers; exit 1 on errors
  python .claude/scripts/wiki.py log <op> <title> [note]  append one entry to wiki/log.md (op: ingest|query|lint|edit)
"""
import datetime, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from verify_claims import LIB, SOURCES_DIR, load_appraised, load_claims, load_source, route_of  # noqa: E402

ROOT = Path.cwd()
WIKI = ROOT / "wiki"
TODAY = datetime.date.today().isoformat()
FOLDERS = {"sources": "Sources", "topics": "Topics", "entities": "Entities", "answers": "Filed answers"}
SPECIAL = {"index", "log", "SCHEMA", "overview"}
GEN_START = "<!-- generated by wiki.py refresh: do not edit between these lines -->"
GEN_END = "<!-- end generated -->"
STUB = "TODO-INGEST"
CITE = re.compile(r"\[(W\d+-\d{3})\b[^\]]*\]")
LINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


# ---------- reading ----------

def library():
    appraised = load_appraised(LIB / "appraised.md")
    claims = load_claims(LIB / "claims_en.md") if (LIB / "claims_en.md").exists() else []
    ids = sorted(p.stem for p in SOURCES_DIR.glob("S-[0-9][0-9][0-9].md") if p.stem != "S-000")
    return ids, appraised, claims


def front_matter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    return dict(re.findall(r"^(\w+):[ \t]*(.*)$", m.group(1), re.M)) if m else {}


def pages():
    """Every wiki page by basename (Obsidian resolves [[links]] by basename)."""
    return {p.stem: p for p in sorted(WIKI.rglob("*.md"))}


def prose(text):
    """The text a person or the LLM wrote: no front matter, no generated block, no code."""
    text = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    text = re.sub(re.escape(GEN_START) + r".*?" + re.escape(GEN_END), "", text, flags=re.S)
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return re.sub(r"`[^`\n]*`", "", text)


def status_of(c):
    if c.get("superseded_by"):
        return f"superseded by {c['superseded_by']}"
    route = route_of(c)
    if route == "PERSON":
        return f"person-checked ({c['verified_by']})" if c.get("verified_by") else "awaiting person check"
    if c.get("translated_by") == "person" and c.get("verified_by"):
        return f"person-entered ({c['verified_by']})"
    return route or "not verified yet"


def cell(s):
    return str(s or "").replace("|", "\\|").replace("\n", " ").strip()


# ---------- generated parts ----------

def facts_block(sid, appraised, claims):
    src = load_source(sid) or {}
    front = dict(re.findall(r"^(\w+):[ \t]*(.*)$", (SOURCES_DIR / f"{sid}.md").read_text(encoding="utf-8").split("excerpt:")[0], re.M))
    row = appraised.get(sid)
    lines = [GEN_START, "", f"**Raw file:** [library/sources/{sid}.md](../../library/sources/{sid}.md) \u00b7 [live page]({src.get('url', '')})", ""]
    lines += ["| field | value |", "| --- | --- |"]
    for key in ("publisher", "type", "language", "retrieved"):
        lines.append(f"| {key} | {cell(front.get(key))} |")
    if row:
        full = next((l for l in (LIB / "appraised.md").read_text(encoding="utf-8").splitlines() if l.strip().startswith(f"| {sid} ")), "")
        c = [x.strip() for x in full.strip().strip("|").split("|")]
        lines.append(f"| rating (credibility / relevance / recency) | {c[1]} / {c[2]} / {c[3]} |")
        lines.append(f"| decision | {row['decision']} |")
    else:
        lines.append("| rating | not appraised yet |")
    lines.append(f"| flagged for human review | {'yes' if src.get('flagged') else 'no'} |")
    mine = [c for c in claims if c.get("source_id") == sid]
    lines += ["", f"**Claims from this source ({len(mine)})**", ""]
    if mine:
        lines += ["| claim | says | evidence | scope | status |", "| --- | --- | --- | --- | --- |"]
        for c in mine:
            lines.append(f"| {c['claim_id']} | {cell(c.get('translation_en'))} | {cell(c.get('evidence'))} | {cell(c.get('scope'))} | {cell(status_of(c))} |")
    else:
        lines.append("None yet: nothing from this source may be stated in the wiki.")
    lines += ["", GEN_END]
    return "\n".join(lines)


def stub(sid):
    title = (load_source(sid) or {}).get("title", "") or sid
    return (f"---\ntitle: \"{sid} \u00b7 {title.replace(chr(34), chr(39))}\"\ntype: source\nsummary: {STUB}\nupdated: {TODAY}\n---\n\n"
            f"# {sid} \u00b7 {title}\n\n## What it says\n\n{STUB}\n\n## Where it fits\n\n{STUB}\n\n{GEN_START}\n{GEN_END}\n")


def index_text(all_pages):
    out = ["---", "title: Index", "type: index", "summary: Catalogue of every wiki page, generated by wiki.py refresh", "---", "",
           "# Index", "", "Generated by `python .claude/scripts/wiki.py refresh`. Do not edit by hand.", "",
           "Start at [[overview]]. The schema is [[SCHEMA]]; the history is [[log]].", ""]
    for folder, heading in FOLDERS.items():
        rows = [(n, p) for n, p in all_pages.items() if p.parent == WIKI / folder]
        out += [f"## {heading} ({len(rows)})", ""]
        for name, p in rows:
            fm = front_matter(p.read_text(encoding="utf-8"))
            summary = fm.get("summary", "").strip().strip('"')
            out.append(f"- [[{name}]] \u2014 {'not ingested yet' if summary == STUB else summary}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def refresh():
    ids, appraised, claims = library()
    made = []
    for sid in ids:
        p = WIKI / "sources" / f"{sid}.md"
        if not p.exists():
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(stub(sid), encoding="utf-8")
            made.append(sid)
        text = p.read_text(encoding="utf-8")
        block = facts_block(sid, appraised, claims)
        if GEN_START in text and GEN_END in text:
            text = re.sub(re.escape(GEN_START) + r".*?" + re.escape(GEN_END), lambda _: block, text, flags=re.S)
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
        p.write_text(text, encoding="utf-8")
    (WIKI / "index.md").write_text(index_text(pages()), encoding="utf-8")
    print(f"refresh: {len(ids)} source pages updated, {len(made)} new stubs ({', '.join(made) or 'none'}), index.md rewritten")


# ---------- status ----------

def cited_ids(all_pages):
    found = {}
    for name, p in all_pages.items():
        if name == "SCHEMA":
            continue
        for cid in CITE.findall(prose(p.read_text(encoding="utf-8"))):
            found.setdefault(cid, set()).add(name)
    return found


def status():
    ids, appraised, claims = library()
    all_pages = pages()
    missing = [s for s in ids if s not in all_pages]
    stubs = [s for s in ids if s in all_pages and STUB in all_pages[s].read_text(encoding="utf-8")]
    cited = cited_ids(all_pages)
    usable = [c for c in claims if not c.get("superseded_by") and route_of(c) != "FAIL"
              and appraised.get(c.get("source_id"), {}).get("decision") == "use"]
    uncited = [c["claim_id"] for c in usable if c["claim_id"] not in cited]
    print("Wiki - sources without a page (run refresh):", ", ".join(missing) or "none")
    print("Wiki - source pages still to ingest:", ", ".join(stubs) or "none")
    print("Wiki - usable claims not yet used anywhere in the wiki:", ", ".join(uncited) or "none")


# ---------- lint ----------

def lint():
    ids, appraised, claims = library()
    by_id = {c["claim_id"]: c for c in claims}
    all_pages = pages()
    errors, warnings, info = [], [], []
    inbound = {n: 0 for n in all_pages}
    awaiting = set()

    for name, p in all_pages.items():
        text = p.read_text(encoding="utf-8")
        rel = p.relative_to(ROOT).as_posix()
        fm = front_matter(text)
        if name not in {"log"} and (not fm.get("title") or not fm.get("summary")):
            errors.append(f"{rel}: front matter needs title and summary")
        if name not in SPECIAL and fm.get("summary", "").strip() == STUB:
            warnings.append(f"{rel}: not ingested yet")
        if name == "SCHEMA":
            continue
        body = prose(text)
        for target in LINK.findall(body):
            target = target.strip()
            if target in all_pages:
                if target != name:
                    inbound[target] += 1
            else:
                errors.append(f"{rel}: broken link [[{target}]]")
        if name in {"index", "log"}:
            continue
        for cid in CITE.findall(body):
            c = by_id.get(cid)
            if not c:
                errors.append(f"{rel}: cites {cid}, which is not in claims_en.md")
            elif c.get("superseded_by"):
                errors.append(f"{rel}: cites {cid}, superseded by {c['superseded_by']}")
            elif route_of(c) == "FAIL":
                errors.append(f"{rel}: cites {cid}, which FAILs verification")
            elif appraised.get(c.get("source_id"), {}).get("decision") != "use":
                errors.append(f"{rel}: cites {cid}, whose source {c.get('source_id')} is not decision: use")
            elif status_of(c) == "awaiting person check":
                awaiting.add(cid)
        for n, line in enumerate(body.splitlines(), 1):
            s = line.strip()
            if not s or s.startswith(("#", "|", "<!--")) or re.search(r"\bW\d+-\d{3}\b", s):
                continue
            words = LINK.sub("", re.sub(r"^(\d+\.|[-*>])\s+", "", s))
            words = re.sub(r"\b(S-\d{3}|W\d+-\d{3}|[A-Z]{2,}\d*|\d{4}-\d{2}-\d{2})\b", "", words)
            words = re.sub(r"(\b(Art(icle)?\.?|criteri(on|a)|stage|week|G)|§)\s*\d+[a-z]?\b", "", words, flags=re.I)
            if re.search(r"\d", words):
                warnings.append(f"{rel}: a number without a claim-id: \"{s[:90]}\"")
        for m in re.finditer(r"(?m)^> \[!contradiction\][^\n]*", body):
            info.append(f"{rel}: {m.group(0)[2:].strip()}")

    for name, count in inbound.items():
        if count == 0 and name not in SPECIAL:
            warnings.append(f"wiki/.../{name}.md: orphan, no page links to it")
    for sid in ids:
        if sid not in all_pages:
            warnings.append(f"{sid}: no wiki page yet (run refresh)")
    if (WIKI / "index.md").exists() and (WIKI / "index.md").read_text(encoding="utf-8") != index_text(all_pages):
        warnings.append("wiki/index.md: out of date (run refresh)")

    for label, items in (("ERROR", errors), ("WARN", warnings), ("NOTE", info)):
        for item in items:
            print(f"{label}: {item}")
    if awaiting:
        print(f"NOTE: {len(awaiting)} cited claims still await a person check; the wiki may show them, Draft may not use them without verified_by")
    print(f"lint: {len(all_pages)} pages, {len(errors)} errors, {len(warnings)} warnings, {len(info)} contradictions flagged")
    return 1 if errors else 0


# ---------- log ----------

def log(op, title, note=""):
    if op not in {"ingest", "query", "lint", "edit"}:
        sys.exit("op must be one of: ingest, query, lint, edit")
    p = WIKI / "log.md"
    entry = f"\n## [{TODAY}] {op} | {title}\n" + (f"\n{note}\n" if note else "")
    with p.open("a", encoding="utf-8") as f:
        f.write(entry)
    print(f"logged: [{TODAY}] {op} | {title}")


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "status":
        status()
    elif cmd == "refresh":
        refresh()
    elif cmd == "lint":
        sys.exit(lint())
    elif cmd == "log" and len(sys.argv) >= 4:
        log(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else "")
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
